### ISSUE TITLE
Cannot join noidea.mooo.com

### ISSUE THREAD

**Issue by NebelNidas** [kyrptonaught/EnchantedToolTips#1]
When trying to join the server this message is being displayed:
![Invalid payload REGISTER](https://user-images.githubusercontent.com/48808497/62470784-75761e80-b79b-11e9-84b7-da029dce7aec.PNG)

I have registered Minecraft and it works with all other servers I've tried. I contacted the server owner, and he suggested a papermc/bukkit incompatibility.

The server log:
```
Couldn't register custom payload
org.bukkit.plugin.messaging.ChannelNameTooLongException: Attempted to send a Plugin Message to a channel that was too large. The maximum length a channel may be is 32 chars (attempted 35 - 'enchantedtooltips:genenchant_packet)
```

**Comment by kyrptonaught** [comment]
Could you try this and report back? https://drive.google.com/file/d/1xI0BNIqZ5gSLFPHOC0bNFY54e_ksjqcS/view?usp=drivesdk

**Comment by NebelNidas** [comment]
This works! Thank you :D
