### ISSUE TITLE
fabric.mod.json defines a non-existing entrypoint for cotton-client-commands

### ISSUE THREAD

**Issue by gbl** [kyrptonaught/EnchantedToolTips#10]
The fabric.mod.json file has the following entry:

```
    "cotton-client-commands": [
      "net.kyrptonaught.enchantedtooltips.GenEnchantsCommand"
    ],

```

which means if any other mod uses cotton client commands, it will crash as soon as CCC tries to execute that entry point.

**Comment by kyrptonaught** [comment]
Fixed, thanks!
