### ISSUE TITLE
[Bug] Enchants are not always displayed sorted

### ISSUE THREAD

**Issue by calloatti** [kyrptonaught/EnchantedToolTips#13]
MC 1.15.2
EnchantedToolTips-1.3.0.jar

With
"Always display enchant info" = false 
"Sort enchant info" = true

You have to press SHIFT to display the enchant info. The problem then is the displayed enchants list is unsorted by default and it only gets sorted when pressing SHIFT.

![image](https://user-images.githubusercontent.com/12817862/84999651-d5618380-b127-11ea-8560-dfad13db039a.png)

![image](https://user-images.githubusercontent.com/12817862/84999671-d98da100-b127-11ea-81bb-63d265d7a158.png)

**Comment by kyrptonaught** [comment]
Ah I misinterpreted your request, uploading 1.3.1 to curse right now
