### ISSUE TITLE
soul_speed enchant missing description

### ISSUE THREAD

**Issue by calloatti** [kyrptonaught/EnchantedToolTips#14]
The new vanilla enchant soul\_speed enchant missing description in EnchantedToolTips-1.3.1-1.16.jar

**Comment by calloatti** [comment]
Also this applies to: 

![](https://user-images.githubusercontent.com/12817862/88464666-0e151b00-ce93-11ea-846b-f42c33dc6607.png)

**Comment by kyrptonaught** [comment]
Ah I completely forget new enchants were added, I’ll add them in a bit

**Comment by kyrptonaught** [comment]
These have been added
