### ISSUE TITLE
Support for other mods (repost)

### ISSUE THREAD

**Issue by SylisMC** [kyrptonaught/EnchantedToolTips#20]
Branching off of [Issue#7](https://github.com/kyrptonaught/EnchantedToolTips/issues/7) would you be willing to include enchant descriptions for other mods if all you had to do was copy-paste? I plan on manually adding descriptions for [Mo'Enchantments](https://www.curseforge.com/minecraft/mc-mods/fabric-more-enchantments) & [Spellbound Enchantments](https://www.curseforge.com/minecraft/mc-mods/Spellbound-Enchantments) for my personal mod pack, but if you're willing to add them for other people's sake, ill give you a list of enchanting names and descriptions provided by the mod makers on their wikis

**Comment by SylisMC** [comment]
[Better End](https://www.curseforge.com/minecraft/mc-mods/betterend)

- "enchantment.betterend.end_veil.desc": "Prevent endermen from getting angry if you look at them"

**Comment by SylisMC** [comment]
[SpellBound](https://www.curseforge.com/minecraft/mc-mods/Spellbound-Enchantments)

- "enchantment.spellbound.dullness.desc": "Dulls tool to prevent hurting pets & companions while mining. Appears on any digging tool, incompatible with other damage enchantments.",
- "enchantment.spellbound.impersonal.desc": "Impersonal teleports the user behind the enemy, allowing you to overwhelm foes without breaking stride. Appears on swords, axes, and tridents.",
- "enchantment.spellbound.jousting.desc": "Jousting is a damage enchantment that makes weapon damage dependent on your velocity relative to your target's. Run down the enemy, or impale them from above! Appears on tridents, compatible with swords, axes, and shovels, incompatible with other damage enchantments.",
- "enchantment.spellbound.launching.desc": "Launching flings the target skywards, turning their own momentum against them. Appears on tridents, compatible with most weapons and tools.",
- "enchantment.spellbound.legacy.desc": "Legacy ensures that your equipment will live on, if only in spirit. If a item with Legacy breaks, it will leave behind a book with all of its enchantments other than Legacy. Appears on all breakables",
- "enchantment.spellbound.monogamous.desc": "Monogamous items form a powerful bond between the enchanted tool and it user, impacting protection, damage, and mining speed as appropriate. Should the user bond with multiple such items, the bond will be severely detrimental. Appears on most weapons, tools, and armor.",
- "enchantment.spellbound.polygamous.desc": "Polygamous items form a bond between the enchanted tool and it user, impacting protection, damage, and mining speed as appropriate. Should the user only have one such bond, the bond will be detrimental. Appears on most weapons, tools, and armor.",
- "enchantment.spellbound.priming.desc": "Priming inflicts Primed for 3 seconds, resetting the duration and increasing severity with every hit to a maximum severity equal to the enchantment's level. Watch your spacing! Appears on tridents, swords, and axes.",
- "enchantment.spellbound.rampage.desc": "Rampage is a damage enchantment that gives the user Green Sparkles for a few seconds whenever you kill a target. Keep moving, kill them all. Appears on tridents, swords, and axes, incompatible with other damage enchantments.",
- "enchantment.spellbound.red_alert.desc": "Red Alert is a protection enchantment that grants the user a shield every several seconds, which will negate the next source of damage. The user's maximum number of shields and generation speed vary with the number of enchanted items and their total Red Alert level. Appears on armor, compatible with shields, incompatible with other protection enchantments.",
- "enchantment.spellbound.rock_collecting.desc": "Rock Collector is an efficiency enchantment that draws power from the ground it breaks. An enchantment for adventurers and nomads, diverse experiences make this enchantment much more powerful. Appears on any digging tool. Incompatible with efficiency and any other enchantment that is incompatible with Efficiency.",
- "enchantment.spellbound.selfish.desc": "Selfish items refuse to remain damaged. If they are missing any durability, they will take it from other items you have equipped. They will not break other items nor take from other selfish items. Appears on all breakables, incompatible with Unbreaking and Mending.",
- "enchantment.spellbound.tethering.desc": "Tethering binds the target to your weapon by inflicting Tethered, pinning them in place or dragging them to you. Great fun, and great utility. Appears on tridents, compatible with swords and axes.",
- "enchantment.spellbound.trophy_collecting.desc": "Trophy Collector is a damage enchantment that draws power from every kill it makes. An enchantment for adventurers and nomads, diverse experiences make this enchantment much more powerful. Appears on tridents, swords, and axes, incompatible with other damage enchantments.",

**Comment by kyrptonaught** [comment]
Some of those descriptions are pretty long, how do they look in game?

**Comment by SylisMC** [comment]
They are fine as long as you use [tooltipfix](https://www.curseforge.com/minecraft/mc-mods/tooltipfix) tooltips kinda suck because the GUI scale will quickly make an items tooltip run of the screen, even if they arent that long

**Comment by SylisMC** [comment]
I could shorten& condense the descriptions if you would like. I just copied their wiki descriptions

**Comment by Tigereye504** [comment]
I've added support for Enchanted Tooltips to Spellbound Enchantments in the upcoming version, so this issue is rather redundant.
