### ISSUE TITLE
Combine `Max Level` line with enchantment title line

### ISSUE THREAD

**Issue by Wdavery** [kyrptonaught/EnchantedToolTips#25]
Instead of adding a new line for the `Max Level` info, consider adding it in the main line, eg. `Title I/III`. 
This screenshot shows what I mean, it's being added by [BetterEnchantedBooks](https://github.com/Bernasss12/BetterEnchantedBooks).
![2021-06-08_13 09 23](https://user-images.githubusercontent.com/12989893/121228559-e46ea380-c85a-11eb-8738-d8d440a62369.png)

Could have it show up only on shift as well.

I think it could help clean up the display a bit, especially on items that have many enchantments.

**Comment by kyrptonaught** [comment]
I prefer not to modify the vanilla tooltip too much, so I added this only when holding shift though. Implemented in 1.3.5 for both 1.16/1.17
