### ISSUE TITLE
Crashing on 1.18.1

### ISSUE THREAD

**Issue by tacogerbil** [kyrptonaught/EnchantedToolTips#32]
Don't know if it's **not** supposed to load up on 1.18.1.  It loads up just fine with only fabric api.
[2021-12-16-1.log](https://github.com/kyrptonaught/EnchantedToolTips/files/7730957/2021-12-16-1.log)

**Comment by kyrptonaught** [comment]
I don't believe this is caused by this mod.

(And this is really old)
