### ISSUE TITLE
[1.18.1] Niche compatibility issue with Limitless

### ISSUE THREAD

**Issue by justastranger** [kyrptonaught/EnchantedToolTips#36]
I figured it would be easiest to report this to you since all it should require is a null check in the right place.

So, with Limitless, there's a possibly-unintended feature that allows you to set the maximum level of an enchantment as can be received from the enchanting table to 0, functionally disabling the enchantment. This, however, does not prevent enchanted books from spawning in loot chests containing those enchantments. From what I can tell, Enchanted Tooltips runs into a null value in place of the maximum enchantment level when attempting to build the tooltip for the books with "disabled" enchantments, resulting in a crash when hovering over it.

[Crash report can be found here](https://paste.ee/p/X7qpN)

**Comment by justastranger** [comment]
My crash report looks awfully similar to #34

**Comment by kyrptonaught** [comment]
Fixed in 1.3.6
