### ISSUE TITLE
Feature request: add Enchanted ToolTips to enchanting table

### ISSUE THREAD

**Issue by calloatti** [kyrptonaught/EnchantedToolTips#4]
Is Unbreaking I the maximum level? What items does in applies to? (The player could be enchanting a book). So many questions... We need an Enchanted Tooltip for this.

![2019-08-14_08 28 12](https://user-images.githubusercontent.com/12817862/63017768-885cb300-be6d-11e9-804e-d2f9b29029c7.png)

**Comment by kyrptonaught** [comment]
Awesome idea as always, will be in the next release

**Comment by kyrptonaught** [comment]
Added in 1.1.0
