### ISSUE TITLE
Add issues link to CurseForge projects

### ISSUE THREAD

**Issue by NebelNidas** [kyrptonaught/EnchantedToolTips#5]
The link sections of your CurseForge projects currently only contain a link to the source code, none directly to the issues:
![Minecraft EnchantedTooltips CurseForge](https://user-images.githubusercontent.com/48808497/64031800-722b4400-cb49-11e9-8121-1b441b2e479d.PNG)
It should be added for the sake of clarity:
![Minecraft REI CurseForge](https://user-images.githubusercontent.com/48808497/64031850-90913f80-cb49-11e9-8af7-f52372df974e.PNG)

**Comment by kyrptonaught** [comment]
Done!
