### ISSUE TITLE
Support for other mods

### ISSUE THREAD

**Issue by mainrs** [kyrptonaught/EnchantedToolTips#7]
Just wanted to bring this up. I think that this mod shouldn't include descriptions from other mods. A better approach (in my opinion) would be to open PRs and add those descriptions to the original mod.

`EnchantedTooltips` could then, if it doesn't find an enchantment, load the lang file from the other mod's jar and see if it finds the key there.

This would remove the need to update this mod if other mods add enchantments and improve maintainability to some degree.

P.S.: relevant lines of code inside of the loader API: [here](https://github.com/FabricMC/fabric-loader/blob/bda2af6e18a210458174a692f9183630f87d6218/src/main/java/net/fabricmc/loader/api/ModContainer.java#L40-L42). Not sure if the loading part is needed. Maybe Fabric does provide the keys that exist in the environment to all mods. I didn't test for this myself.

If you want to add this change I would happily contribute to the project :)

**Comment by kyrptonaught** [comment]
It already is possible for other mods to add their own enchant descriptions, I'd prefer if the other mods added the descriptions themselves actually. I only included some of the more popular ones and don't plan to add any others. It seems like not too many other mods are adding enchants though. 

I think I will create some PRs though adding them to their respective mods to get the ball rolling
